"""main

Revision ID: e16fbaeaab2b
Revises: 
Create Date: 2026-06-21 12:34:25.671940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16fbaeaab2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crag_slug', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('sector_name', sa.String(), nullable=True),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('climb',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_id', sa.INTEGER(), nullable=False, foreign_key='area.id'),
    sa.Column('average_grade', sa.Float(), nullable=False),
    sa.Column('flash_rate', sa.Float(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('total_ascents', sa.INTEGER(), nullable=False),
    sa.Column('recommended_rate', sa.Float(), nullable=False),
    sa.Column('jan_ascents', sa.INTEGER(), nullable=False),
    sa.Column('feb_ascents', sa.INTEGER(), nullable=False),
    sa.Column('mar_ascents', sa.INTEGER(), nullable=False),
    sa.Column('apr_ascents', sa.INTEGER(), nullable=False),
    sa.Column('may_ascents', sa.INTEGER(), nullable=False),
    sa.Column('jun_ascents', sa.INTEGER(), nullable=False),
    sa.Column('jul_ascents', sa.INTEGER(), nullable=False),
    sa.Column('aug_ascents', sa.INTEGER(), nullable=False),
    sa.Column('sep_ascents', sa.INTEGER(), nullable=False),
    sa.Column('oct_ascents', sa.INTEGER(), nullable=False),
    sa.Column('nov_ascents', sa.INTEGER(), nullable=False),
    sa.Column('dec_ascents', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climb')
    op.drop_table('area')
    # ### end Alembic commands ###
